### ISSUE TITLE
add 2 buttons to pyradiomics page right under the heading image

### ISSUE THREAD

**Issue by ahmedhosny** [Radiomics/radiomics.github.io#16]
see http://jupyter.org/

button 1 will say "try it now" and will take you to a static ipython notebook (in the future, we can look at possibility of a live demo with a preloaded dataset, where users can actually run the cells)

button 2 will say something like "get it now" and will point to installation instructions directly

**Comment by JoostJM** [comment]
@ahmedhosny As to the static ipython notebook, I uploaded an html version of the example notebook I used in the google drive, can you use that one?

**Comment by ahmedhosny** [comment]
via #21
